<!DOCTYPE catalog [
  <!ELEMENT catalog (product+)>
  <!ELEMENT product (image, model, brand, price)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT model (#PCDATA)>
  <!ELEMENT brand (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
]>

<catalog>
  <product>
    <image>./images/page1/air_force_1.png</image>
    <model>Air Force 1</model>
    <brand>Nike</brand>
    <price>$100</price>
  </product>
  <product>
    <image>./images/page1/ultra_boost.png</image>
    <model>Ultra Boost</model>
    <brand>Adidas</brand>
    <price>$120</price>
  </product>
  <product>
    <image>./images/page1/reebok.png</image>
    <model>Classic Leather</model>
    <brand>Reebok</brand>
    <price>$80</price>
  </product>
  <product>
    <image>./images/page1/vans.png</image>
    <model>Old Skool</model>
    <brand>Vans</brand>
    <price>$65</price>
  </product>
  <product>
    <image>./images/page1/dunk_verde.png</image>
    <model>Dunk Low</model>
    <brand>Nike</brand>
    <price>$100</price>
  </product>
  <product>
    <image>./images/page1/campus.png</image>
    <model>Campus</model>
    <brand>Adidas</brand>
    <price>$110</price>
  </product>
  <product>
    <image>./images/page1/550.png</image>
    <model>550</model>
    <brand>New Balance</brand>
    <price>$150</price>
  </product>
  <product>
    <image>./images/page1/forum.png</image>
    <model>Forum</model>
    <brand>Adidas</brand>
    <price>$120</price>
  </product>
  <product>
    <image>./images/page1/2002r.png</image>
    <model>2002r</model>
    <brand>New Balance</brand>
    <price>$160</price>
  </product>
</catalog>
